name: ADF - build & deploy 
on:
  workflow_dispatch:
  push:
    branches:
      - Feature/create ci/cd

permissions:
      id-token: write
      contents: read

jobs:
  
  deploy_ARM_Template:
    runs-on: ubuntu-latest
    steps:  
      - name: Login via Az module
        uses: azure/login@v1

        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }} 
          dataFactoryName: ${{ vars.DATA_FACTORY_NAME }}
          armTemplateFile: ADF_template/ARMTemplateForFactory.json 
          armTemplateParametersFile: ADF_template/ARMTemplateParametersForFactory.json 
          additionalParameters: 'factoryName="${{vars.DATA_FACTORY_NAME}}"'
